title: Dario Rodighiero
excerpt_separator: "<!--more-->"
description: Design, Data, and Humanities
url: https://dariorodighiero.com

plugins:
  - jekyll-redirect-from
  - jekyll-feed

feed:
  collections:
    - projects

collections:
  projects:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
